# Generated by Django 4.2 on 2023-11-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfielImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام تصویر')),
                ('img', models.ImageField(upload_to='images/', verbose_name='تصویر پروفایل')),
            ],
            options={
                'verbose_name': 'تصاویر پروفایل',
                'verbose_name_plural': 'تصاویر پروفایل',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='نام کاربری')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=100, verbose_name='ایمیل')),
                ('id_number', models.FloatField(blank=True, null=True, verbose_name='کد ملی')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('birth_date', models.DateTimeField(verbose_name='تاریخ تولد')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_admin', models.BooleanField(default=True, verbose_name='مدیر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_student', models.BooleanField(default=True, verbose_name='دانشجو')),
                ('password1', models.CharField(max_length=150, verbose_name='رمز عبور')),
                ('password2', models.CharField(max_length=150, verbose_name='تایید رمز عبور')),
                ('groups', models.ManyToManyField(blank=True, related_name='groups', to='auth.group', verbose_name='گروه\u200cها')),
                ('profile_img', models.ManyToManyField(to='accounts.profielimages', verbose_name='تصویر پروفایل')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission', verbose_name='دسترسی\u200cها')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
        ),
    ]
