# Generated by Django 4.2.7 on 2023-11-11 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_options_alter_user_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_number',
            field=models.FloatField(blank=True, null=True, verbose_name='کد ملی'),
        ),
    ]
