# Generated by Django 4.2.7 on 2023-11-11 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClassCategory',
        ),
        migrations.DeleteModel(
            name='Classes',
        ),
        migrations.DeleteModel(
            name='ImageClass',
        ),
        migrations.DeleteModel(
            name='VideoClass',
        ),
    ]
