# Generated by Django 4.2.7 on 2023-11-11 18:29

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی کلاس ها',
                'verbose_name_plural': 'دسته بندی کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام تصویر')),
                ('image', models.FileField(upload_to='images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصاویر کلاس ها',
                'verbose_name_plural': 'تصاویر کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='VideoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام فیلم')),
                ('video', models.FileField(upload_to='media/', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'فیلم های کلاس ها',
                'verbose_name_plural': 'فیلم های کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام کلاس')),
                ('text', tinymce.models.HTMLField(verbose_name='توضیحات کلاس')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.imageclass', verbose_name='تصاویر کلاس')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.videoclass', verbose_name='فیلم های کلاس')),
            ],
            options={
                'verbose_name': 'کلاس ها',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
    ]
