# Generated by Django 4.2 on 2023-11-14 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام دسته')),
            ],
            options={
                'verbose_name': 'دسته بندی کلاس ها',
                'verbose_name_plural': 'دسته بندی کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='ImageClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام تصویر')),
                ('image', models.FileField(upload_to='images/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصاویر کلاس ها',
                'verbose_name_plural': 'تصاویر کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='VideoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام فیلم')),
                ('video', models.FileField(upload_to='media/', verbose_name='فیلم')),
            ],
            options={
                'verbose_name': 'فیلم های کلاس ها',
                'verbose_name_plural': 'فیلم های کلاس ها',
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='نام کلاس')),
                ('text', tinymce.models.HTMLField(verbose_name='توضیحات کلاس')),
                ('display', models.BooleanField(default=False, verbose_name='نمایش داده شود؟؟')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.classcategory', verbose_name='دسته بندی کلاس')),
                ('img', models.ManyToManyField(blank=True, to='class.imageclass', verbose_name='تصاویر کلاس')),
                ('selected_video', models.ManyToManyField(blank=True, help_text='لطفا بعد از کامل کردن تمامی فیلدها و ذخیره کلاس این فیلد را کامل کنید!!', related_name='selected_videos', to='class.videoclass', verbose_name='فیلم های انتخاب شده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
                ('video', models.ManyToManyField(blank=True, to='class.videoclass', verbose_name='فیلم های کلاس')),
            ],
            options={
                'verbose_name': 'کلاس ها',
                'verbose_name_plural': 'کلاس ها',
            },
        ),
    ]
