# Generated by Django 4.2 on 2023-11-14 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='selected_video',
        ),
    ]
