# Generated by Django 4.2.7 on 2023-11-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='img',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='video',
        ),
        migrations.AddField(
            model_name='classes',
            name='img',
            field=models.ManyToManyField(blank=True, to='class.imageclass', verbose_name='تصاویر کلاس'),
        ),
        migrations.AddField(
            model_name='classes',
            name='video',
            field=models.ManyToManyField(blank=True, to='class.videoclass', verbose_name='فیلم های کلاس'),
        ),
    ]
