# Generated by Django 4.2.7 on 2023-11-11 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_remove_classes_img_remove_classes_video_classes_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='class.classcategory', verbose_name='دسته بندی کلاس'),
            preserve_default=False,
        ),
    ]
