# Generated by Django 4.2 on 2023-11-14 17:42

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0002_remove_classes_selected_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclass',
            name='text',
            field=tinymce.models.HTMLField(default=2, verbose_name='توضیحات فیلم'),
            preserve_default=False,
        ),
    ]
