# Generated by Django 4.2 on 2023-11-12 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('class', '0003_classes_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tinymce.models.HTMLField(verbose_name='نام دوره')),
                ('time_added', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('time_spend', models.DateTimeField(auto_now_add=True, verbose_name='مدت زمان پیشنهادی دوره')),
                ('lesson', models.ManyToManyField(to='class.classes', verbose_name='درس های دوره')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='دانشجو')),
            ],
            options={
                'verbose_name': 'دوره ها',
                'verbose_name_plural': 'دوره ها',
            },
        ),
    ]
