# Generated by Django 4.2 on 2023-11-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_videoclass_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='total_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='مدت زمان کل دوره'),
        ),
    ]
