# Generated by Django 4.2 on 2023-11-12 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='time_spend',
        ),
    ]
