# Generated by Django 4.2 on 2023-11-18 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0004_classes_total_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'video category',
                'verbose_name_plural': 'video category',
            },
        ),
        migrations.AddField(
            model_name='videoclass',
            name='video_category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='class.videocategory'),
            preserve_default=False,
        ),
    ]
