# Generated by Django 4.2 on 2023-11-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_remove_course_time_spend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='lesson',
            new_name='classes',
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.course')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='class.videoclass')),
            ],
            options={
                'verbose_name': 'ویدیوهای دوره',
                'verbose_name_plural': 'ویدیوهای دوره',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='videos',
            field=models.ManyToManyField(blank=True, through='class.CourseVideo', to='class.videoclass', verbose_name='ویدیوهای دوره'),
        ),
    ]
