# Generated by Django 4.2 on 2023-11-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0005_videocategory_videoclass_video_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoclass',
            name='video_link',
            field=models.CharField(default=2, max_length=550, verbose_name='لینک فیلم'),
            preserve_default=False,
        ),
    ]
