# Generated by Django 4.2 on 2023-11-18 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_videoclass_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoclass',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='media/', verbose_name='فیلم'),
        ),
        migrations.AlterField(
            model_name='videoclass',
            name='video_link',
            field=models.CharField(blank=True, max_length=550, null=True, verbose_name='لینک فیلم'),
        ),
    ]
